# Generated by Django 5.1.5 on 2025-02-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_of_issue', models.DateTimeField(auto_now_add=True)),
                ('author_of_book', models.CharField(max_length=100, null=True)),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('issue_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name_of_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_LMS.book_details')),
            ],
        ),
    ]
