# Generated by Django 5.1.5 on 2025-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=20)),
                ('time_of_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
