# Generated by Django 5.1.5 on 2025-01-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={},
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
