# Generated by Django 5.1.5 on 2025-02-10 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0002_issuebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('date_of_submission', models.DateField()),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('book_name', models.ForeignObject(from_fields=['Date_of_issue'], on_delete=django.db.models.deletion.SET_NULL, related_name='book_submission', to='api_LMS.issuebook', to_fields=['college_name'])),
            ],
        ),
    ]
