# Generated by Django 5.1.5 on 2025-02-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0002_staffdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_submission',
            name='issued_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_issue', to='api_LMS.issuebook'),
        ),
    ]
