# Generated by Django 5.1.5 on 2025-02-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0003_book_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_submission',
            name='book_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_submission', to='api_LMS.issuebook'),
        ),
    ]
