# Generated by Django 5.1.5 on 2025-02-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0003_alter_book_submission_issued_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_submission',
            name='submiited',
            field=models.BooleanField(default=False),
        ),
    ]
