# Generated by Django 5.1.5 on 2025-02-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0003_alter_userregistration_photo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
