# Generated by Django 5.1.5 on 2025-04-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0004_book_submission_submiited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_details',
            name='book_photo',
            field=models.ImageField(null=True, upload_to='book_details/'),
        ),
    ]
