# Generated by Django 5.1.5 on 2025-02-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_LMS', '0006_alter_userregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
